name: Build Single Popular App

env:
  NODE_VERSION: "22"
  PNPM_VERSION: "10.26.2"

on:
  workflow_dispatch:
    inputs:
      name:
        description: "App Name"
        required: true
        default: "tasheer"

      title:
        description: "App Title"
        required: true
        default: "Tasheer"

      name_zh:
        description: "App Name in Chinese"
        required: true
        default: "تأشير"

      url:
        description: "App URL"
        required: true
        default: "https://vc.tasheer.com/"

      icon:
        description: "App Icon"
        required: false

      new_window:
        description: "Allow sites to open new windows"
        required: false
        default: true

      incognito:
        description: "Enable incognito mode"
        required: false
        default: false

      width:
        description: "Window width"
        required: false
        default: 1400

      height:
        description: "Window height"
        required: false
        default: 900
